### ISSUE TITLE
question about overwrite the logback configruation

### ISSUE THREAD

**Issue by fishjam** [cn-panda/logbackRceDemo#3]
我有个问题，如果黑客能够覆盖 logback 的配置文件，那覆盖 .jar 或 .class 岂不是更好？

**Comment by cn-panda** [comment]
这个只是一个 DEMO 而已，只是说明了一个场景，没必要较真
最高权限，如果要覆盖，我直接利用这个去覆盖定时任务文件反弹 shell 不是更好

**Comment by fishjam** [comment]
所以说，完全不是问题的“问题”，被这么一搞，在log4j shell还搞得大家草木皆兵的时候，领导看到你提交的这个“问题”，让我们所有使用 logback 的团队也要升级项目，简直了。。。

**Comment by cn-panda** [comment]
尴尬了，实际上这个洞只是在我看 Log4j 的时候，横向移动看到的，然后提出了一种具体演示场景，其实官方有说明呀，说明了危害很低

**Comment by cn-panda** [comment]
> 所以说，完全不是问题的“问题”，被这么一搞，在log4j shell还搞得大家草木皆兵的时候，领导看到你提交的这个“问题”，让我们所有使用 logback 的团队也要升级项目，简直了。。。

理解……tnl
